### PR TITLE
Ensure tree-shaking changing the export *

### PR DESCRIPTION
**Pull request by squelix**
I don't think `angular-animations` can be tree shakable, so to avoid to import all the lib with a single animation, i think it could be better this way ;)

### CODE REVIEW

**Comment by filipows** [comment]
Hi @squelix, 
thanks for your contribution! 
I think I need to educate myself a bit more about webpack's tree-shaking as I was thinking that `export * from 'module'` wouldn't harm its capabilities. Have you done tests or found articles/issues that mention that? 

I googled quickly and found only this closed issue https://github.com/webpack/webpack/issues/2847 which confirms it used to be a problem, but has been fixed some time ago.

**Comment by squelix** [comment]
You are using `ng-packgr` not `webpack` to build this lib and in their doc, they are saying this https://github.com/ng-packagr/ng-packagr/blob/master/docs/entry-file.md

**Comment by filipows** [comment]
You're right, `ng-packgr` uses rollup for bundling. I read the mentioned doc, but I can't find any information about tree-shaking or about avoiding `export * from 'module'`. 
Maybe it would be good to create a simple project and test that.

**Comment by filipows** [comment]
Hi @squelix ,

I finally found some time to get back to your PR.
I've tested 2 versions of the library (with specific exports and exports with "*") on a medium-size angular project (using Angular 10 with Ivy) and there was no difference in the build sizes that I could see.

However, I came across compilation issues related to conflicting namespaces after updating to Angular 10 and the current version of ng-packgr. I found also [a comment by one of the Angular devs](https://github.com/angular/angular/issues/33668#issuecomment-555973301) that manually re-exporting all objects is currently the suggested approach. So considering all that, I decided to go ahead and merge your changes.

Thank you for your contribution once again!

**Pull request merged**
